examples:
  - text: "SN0015-08 井录井完井报告"
    label: '{"well_name": {"SN0015-08": [[0, 8]]}}'
  - text: "评审单位：长庆油田苏里格南作业分公司地学部"
    label: '{"block": {"苏里格南作业分公司": [[9, 17]]}}'
  - text: "古生界二叠系下统山西组"
    label: '{"strat_unit": {"山西组": [[8, 10]]}}'
  - text: "云岩：成份中白云石约占85.2~90.4%"
    label: '{"lithology": {"云岩": [[0, 1]]}}'
  - text: "岩性特征：棕红色泥岩、砂质泥岩，浅棕红色细砂岩、泥质砂岩"
    label: '{"lithology_color": {"棕红色": [[5, 7]], "浅棕红色": [[16, 19]]}}'
  - text: "岩性特征：棕红色泥岩、砂质泥岩，浅棕红色细砂岩、泥质砂岩"
    label: '{"lithology_texture": {"砂质": [[11, 12]], "泥质": [[24, 25]]}}'
